services:
  - type: web
    name: an-law-firm
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run render-build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: an-law-firm-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"

databases:
  - name: an-law-firm-db
    plan: free
    region: oregon
