// Permission definitions
export const PERMISSIONS = [
  { key: "createMatter",          category: "matter",  description: "Create matters",                 descriptionAr: "إنشاء مسائل" },
  { key: "approveMatter",         category: "matter",  description: "Approve matters",                descriptionAr: "اعتماد المسائل" },
  { key: "activateMatter",        category: "matter",  description: "Activate approved matters",      descriptionAr: "تفعيل المسائل المعتمدة" },
  { key: "editApprovedMatter",    category: "matter",  description: "Edit approved matters",          descriptionAr: "تعديل المسائل المعتمدة" },
  { key: "deleteMatter",          category: "matter",  description: "Delete matters",                 descriptionAr: "حذف المسائل" },
  { key: "assignTeamMembers",     category: "matter",  description: "Assign team members",            descriptionAr: "تعيين أعضاء الفريق" },
  { key: "viewFinancialReports",  category: "billing", description: "View financial reports",         descriptionAr: "عرض التقارير المالية" },
  { key: "generateInvoices",      category: "billing", description: "Generate invoices",              descriptionAr: "إنشاء فواتير" },
  { key: "manageBilling",         category: "billing", description: "Manage billing",                 descriptionAr: "إدارة الفوترة" },
  { key: "managePermissions",     category: "system",  description: "Manage permissions",             descriptionAr: "إدارة الصلاحيات" },
  { key: "manageUsers",           category: "system",  description: "Manage users",                   descriptionAr: "إدارة المستخدمين" },
  { key: "systemSettings",        category: "system",  description: "System settings",                descriptionAr: "إعدادات النظام" },
  { key: "addTimeEntry",          category: "time",    description: "Add time entries",               descriptionAr: "إضافة إدخالات الوقت" },
  { key: "viewOwnTimeEntries",    category: "time",    description: "View own time entries",          descriptionAr: "عرض إدخالات الوقت الخاصة" },
  { key: "viewOthersTimeEntries", category: "time",    description: "View others time entries",       descriptionAr: "عرض إدخالات وقت الآخرين" },
  { key: "editOwnTimeEntries",    category: "time",    description: "Edit own time entries",          descriptionAr: "تعديل إدخالات الوقت الخاصة" },
  { key: "editOthersTimeEntries", category: "time",    description: "Edit others time entries",       descriptionAr: "تعديل إدخالات وقت الآخرين" },
  { key: "approveTimeEntries",    category: "time",    description: "Approve time entries",           descriptionAr: "اعتماد إدخالات الوقت" },
  { key: "rejectTimeEntries",     category: "time",    description: "Reject time entries",            descriptionAr: "رفض إدخالات الوقت" },
  { key: "lockBilledEntries",     category: "billing", description: "Lock billed time entries",       descriptionAr: "تأمين إدخالات الوقت المفوترة" },
  { key: "viewBillingRates",      category: "billing", description: "View billing rates",             descriptionAr: "عرض أسعار الفوترة" },
  { key: "modifyBillingRates",    category: "billing", description: "Modify billing rates",           descriptionAr: "تعديل أسعار الفوترة" },
  { key: "viewMatterContent",     category: "matter",  description: "View matter content",            descriptionAr: "عرض محتوى المسائل" },
  { key: "viewClientConfidential",category: "matter",  description: "View confidential client info",  descriptionAr: "عرض معلومات العميل السرية" },
  { key: "viewAuditLog",          category: "system",  description: "View audit log",                 descriptionAr: "عرض سجل التدقيق" },
  { key: "editPermissions",       category: "system",  description: "Edit permissions matrix",        descriptionAr: "تعديل مصفوفة الصلاحيات" },
  { key: "viewOwnReports",        category: "reports", description: "View own time and performance reports",         descriptionAr: "عرض التقارير الشخصية" },
  { key: "viewDepartmentReports", category: "reports", description: "View reports for own department employees",     descriptionAr: "عرض تقارير موظفي القسم" },
  { key: "viewAllReports",        category: "reports", description: "View firm-wide reports across all departments", descriptionAr: "عرض تقارير الشركة الكاملة" },
];

type PermGrant = {
  granted: boolean;
  scope?: string;
  isLocked?: boolean;
  lockedDirection?: string;
};

// Permission matrix per role: key -> PermGrant
export const ROLE_MATRIX: Record<string, Record<string, PermGrant>> = {
  PARTNER: Object.fromEntries(
    PERMISSIONS.map((p) => [p.key, { granted: true, scope: "ALL", isLocked: true, lockedDirection: "ON" }])
  ),

  SYSTEM_ADMIN: {
    createMatter:          { granted: false },
    approveMatter:         { granted: false },
    activateMatter:        { granted: false },
    editApprovedMatter:    { granted: false },
    deleteMatter:          { granted: false },
    assignTeamMembers:     { granted: false },
    viewFinancialReports:  { granted: false, isLocked: true, lockedDirection: "OFF" },
    generateInvoices:      { granted: false },
    manageBilling:         { granted: false, isLocked: true, lockedDirection: "OFF" },
    managePermissions:     { granted: true, scope: "ALL", isLocked: true, lockedDirection: "ON" },
    manageUsers:           { granted: true, scope: "ALL", isLocked: true, lockedDirection: "ON" },
    systemSettings:        { granted: true, scope: "ALL", isLocked: true, lockedDirection: "ON" },
    addTimeEntry:          { granted: false },
    viewOwnTimeEntries:    { granted: false },
    viewOthersTimeEntries: { granted: false },
    editOwnTimeEntries:    { granted: false },
    editOthersTimeEntries: { granted: false },
    approveTimeEntries:    { granted: false },
    rejectTimeEntries:     { granted: false },
    lockBilledEntries:     { granted: false },
    viewBillingRates:      { granted: false },
    modifyBillingRates:    { granted: false },
    viewMatterContent:     { granted: false, isLocked: true, lockedDirection: "OFF" },
    viewClientConfidential:{ granted: false, isLocked: true, lockedDirection: "OFF" },
    viewAuditLog:          { granted: true, scope: "ALL", isLocked: true, lockedDirection: "ON" },
    editPermissions:       { granted: true, scope: "ALL", isLocked: true, lockedDirection: "ON" },
    viewOwnReports:        { granted: false, isLocked: true, lockedDirection: "OFF" },
    viewDepartmentReports: { granted: false, isLocked: true, lockedDirection: "OFF" },
    viewAllReports:        { granted: false, isLocked: true, lockedDirection: "OFF" },
  },

  DEPARTMENT_MANAGER: {
    createMatter:          { granted: true, scope: "OWN_DEPARTMENT" },
    approveMatter:         { granted: true, scope: "OWN_DEPARTMENT" },
    activateMatter:        { granted: true, scope: "OWN_DEPARTMENT" },
    editApprovedMatter:    { granted: true, scope: "OWN_DEPARTMENT" },
    deleteMatter:          { granted: false },
    assignTeamMembers:     { granted: true, scope: "OWN_DEPARTMENT" },
    viewFinancialReports:  { granted: false },
    generateInvoices:      { granted: false },
    manageBilling:         { granted: false },
    managePermissions:     { granted: false },
    manageUsers:           { granted: false },
    systemSettings:        { granted: false },
    addTimeEntry:          { granted: true, scope: "ALL" },
    viewOwnTimeEntries:    { granted: true, scope: "ALL" },
    viewOthersTimeEntries: { granted: true, scope: "OWN_DEPARTMENT" },
    editOwnTimeEntries:    { granted: true, scope: "ALL" },
    editOthersTimeEntries: { granted: true, scope: "OWN_DEPARTMENT" },
    approveTimeEntries:    { granted: true, scope: "OWN_DEPARTMENT" },
    rejectTimeEntries:     { granted: true, scope: "OWN_DEPARTMENT" },
    lockBilledEntries:     { granted: false },
    viewBillingRates:      { granted: true, scope: "OWN_DEPARTMENT" },
    modifyBillingRates:    { granted: false },
    viewMatterContent:     { granted: true, scope: "OWN_DEPARTMENT" },
    viewClientConfidential:{ granted: false },
    viewAuditLog:          { granted: false },
    editPermissions:       { granted: false },
    viewOwnReports:        { granted: true, scope: "OWN" },
    viewDepartmentReports: { granted: true, scope: "OWN_DEPARTMENT" },
    viewAllReports:        { granted: false },
  },

  EMPLOYEE: {
    createMatter:          { granted: true, scope: "ALL" },
    approveMatter:         { granted: false },
    activateMatter:        { granted: false },
    editApprovedMatter:    { granted: false },
    deleteMatter:          { granted: false },
    assignTeamMembers:     { granted: false },
    viewFinancialReports:  { granted: false },
    generateInvoices:      { granted: false },
    manageBilling:         { granted: false },
    managePermissions:     { granted: false },
    manageUsers:           { granted: false },
    systemSettings:        { granted: false },
    addTimeEntry:          { granted: true, scope: "ALL" },
    viewOwnTimeEntries:    { granted: true, scope: "ALL" },
    viewOthersTimeEntries: { granted: false },
    editOwnTimeEntries:    { granted: true, scope: "ALL" },
    editOthersTimeEntries: { granted: false },
    approveTimeEntries:    { granted: false },
    rejectTimeEntries:     { granted: false },
    lockBilledEntries:     { granted: false },
    viewBillingRates:      { granted: false },
    modifyBillingRates:    { granted: false },
    viewMatterContent:     { granted: true, scope: "OWN" },
    viewClientConfidential:{ granted: false },
    viewAuditLog:          { granted: false },
    editPermissions:       { granted: false },
    viewOwnReports:        { granted: true, scope: "OWN" },
    viewDepartmentReports: { granted: false },
    viewAllReports:        { granted: false },
  },

  ADMIN_STAFF: {
    createMatter:          { granted: false },
    approveMatter:         { granted: false },
    activateMatter:        { granted: false },
    editApprovedMatter:    { granted: false },
    deleteMatter:          { granted: false },
    assignTeamMembers:     { granted: false },
    viewFinancialReports:  { granted: false },
    generateInvoices:      { granted: false },
    manageBilling:         { granted: false },
    managePermissions:     { granted: false },
    manageUsers:           { granted: false },
    systemSettings:        { granted: false },
    addTimeEntry:          { granted: true, scope: "PARTIAL" },
    viewOwnTimeEntries:    { granted: true, scope: "ALL" },
    viewOthersTimeEntries: { granted: false },
    editOwnTimeEntries:    { granted: true, scope: "ALL" },
    editOthersTimeEntries: { granted: false },
    approveTimeEntries:    { granted: false },
    rejectTimeEntries:     { granted: false },
    lockBilledEntries:     { granted: false },
    viewBillingRates:      { granted: false },
    modifyBillingRates:    { granted: false },
    viewMatterContent:     { granted: false },
    viewClientConfidential:{ granted: false },
    viewAuditLog:          { granted: false },
    editPermissions:       { granted: false },
    viewOwnReports:        { granted: false },
    viewDepartmentReports: { granted: false },
    viewAllReports:        { granted: false },
  },

  ACCOUNTANT: {
    createMatter:          { granted: false },
    approveMatter:         { granted: false },
    activateMatter:        { granted: false },
    editApprovedMatter:    { granted: false },
    deleteMatter:          { granted: false },
    assignTeamMembers:     { granted: false },
    viewFinancialReports:  { granted: true, scope: "ALL" },
    generateInvoices:      { granted: true, scope: "ALL" },
    manageBilling:         { granted: true, scope: "ALL" },
    managePermissions:     { granted: false },
    manageUsers:           { granted: false },
    systemSettings:        { granted: false },
    addTimeEntry:          { granted: true, scope: "ALL" },
    viewOwnTimeEntries:    { granted: true, scope: "ALL" },
    viewOthersTimeEntries: { granted: true, scope: "PARTIAL" },
    editOwnTimeEntries:    { granted: true, scope: "ALL" },
    editOthersTimeEntries: { granted: false },
    approveTimeEntries:    { granted: false },
    rejectTimeEntries:     { granted: false },
    lockBilledEntries:     { granted: true, scope: "ALL" },
    viewBillingRates:      { granted: true, scope: "ALL" },
    modifyBillingRates:    { granted: true, scope: "ALL" },
    viewMatterContent:     { granted: false },
    viewClientConfidential:{ granted: false },
    viewAuditLog:          { granted: false },
    editPermissions:       { granted: false },
    viewOwnReports:        { granted: true, scope: "OWN" },
    viewDepartmentReports: { granted: false, isLocked: true, lockedDirection: "OFF" },
    viewAllReports:        { granted: false, isLocked: true, lockedDirection: "OFF" },
  },
};

export const ROLES_DEF = [
  { name: "PARTNER",            nameAr: "شريك",               isLocked: true  },
  { name: "SYSTEM_ADMIN",       nameAr: "مسؤول النظام",        isLocked: true  },
  { name: "DEPARTMENT_MANAGER", nameAr: "مدير الإدارة",        isLocked: false },
  { name: "EMPLOYEE",           nameAr: "موظف",                isLocked: false },
  { name: "ADMIN_STAFF",        nameAr: "موظف إداري",          isLocked: false },
  { name: "ACCOUNTANT",         nameAr: "محاسب",               isLocked: false },
];
